export const ActionTypes = {
    FETCH_REQUEST: 'UNITS_REQUEST',
    FETCH_SUCCESS: 'UNITS_FETCH_SUCCESS',
    FETCH_FAIL: 'UNITS_FETCH_FAIL',
    FETCH_DETAIL_REQUEST: 'UNITS_FETCH_DETAIL_REQUEST',
    FETCH_DETAIL_SUCCESS: 'UNITS_FETCH_DETAIL_SUCCESS',
    FETCH_DETAIL_FAIL: 'UNITS_FETCH_DETAIL_FAIL',
    UPDATE_UNITS_BY_FILTERS: 'UPDATE_UNITS_BY_FILTERS',
    RESET_FILTERS: 'UNITS_RESET_FILTERS',
    UPDATE_AGE_FILTER: 'UNITS_UPDATE_AGE_FILTER',
    UPDATE_COSTS_FILTER: 'UNITS_UPDATE_COSTS_FILTER',
};